version: 2
updates:
    - package-ecosystem: github-actions
      commit-message:
          include: scope
          prefix: ci
      directory: /
      open-pull-requests-limit: 20
      schedule:
          interval: monthly

    - package-ecosystem: npm
      commit-message:
          include: scope
          prefix: build
      directory: /
      ignore:
          - dependency-name: esbuild
          - dependency-name: esbuild-plugin-glob
          # Below are deps that have migrate to ESM in their
          # next major version so we can't use them
          - dependency-name: file-type
            update-types: version-update:semver-major
          - dependency-name: is-html
            update-types: version-update:semver-major
      open-pull-requests-limit: 20
      schedule:
          interval: monthly
